In [2]:
import numpy as np

In [3]:
array = np.array([[1,2,3],
                 [4,5,6],
                  [3,4,5]])
print(array)

[[1 2 3]
 [4 5 6]
 [3 4 5]]


In [4]:
print(array.ndim)#维度

2


In [5]:
array.shape#形状

(3, 3)

In [6]:
array.size#大小（元素个数）

9

In [7]:
array.dtype#元素类型

dtype('int32')

In [9]:
a = np.array([1,2,3],dtype=np.int32)
a.dtype

dtype('int32')

In [10]:
b = np.array([1,2,3],dtype=np.float32)
b.dtype

dtype('float32')

In [12]:
c = np.array([1,2,3])#一维数据
d = np.array([[1,2,3],[2,4,5]])#二维数据
d

array([[1, 2, 3],
       [2, 4, 5]])

In [13]:
zeros = np.zeros((2,3))#生成两行三列的0矩阵
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
ones = np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
empty = np.empty((3,2))
print(empty)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [19]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
b = np.arange(4,12,2)#从4开始步长为2输出小于12的数
b

array([ 4,  6,  8, 10])

In [22]:
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
a1 = np.array([[1,2,3,4],[2,3,4,5]])
a2 = np.array([[0,9,8,7],[3,4,5,6]])
print("a1:",a1)
print("a2:",a2)

a1: [[1 2 3 4]
 [2 3 4 5]]
a2: [[0 9 8 7]
 [3 4 5 6]]


In [25]:
a1+a2

array([[ 1, 11, 11, 11],
       [ 5,  7,  9, 11]])

In [26]:
a1-a2

array([[ 1, -7, -5, -3],
       [-1, -1, -1, -1]])

In [27]:
a1*a2

array([[ 0, 18, 24, 28],
       [ 6, 12, 20, 30]])

In [28]:
a1**a2

array([[    1,   512,  6561, 16384],
       [    8,    81,  1024, 15625]], dtype=int32)

In [29]:
a1/a2

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       inf, 0.22222222, 0.375     , 0.57142857],
       [0.66666667, 0.75      , 0.8       , 0.83333333]])

In [30]:
a2//a1#取整

array([[0, 4, 2, 1],
       [1, 1, 1, 1]], dtype=int32)

In [31]:
a2%a1#取余

array([[0, 1, 2, 3],
       [1, 1, 1, 1]], dtype=int32)

In [32]:
a1>3

array([[False, False, False,  True],
       [False, False,  True,  True]])

In [36]:
a = np.arange(12).reshape((4,3))#矩阵乘法
b = np.ones((3,4))
np.dot(a,b)

array([[ 3.,  3.,  3.,  3.],
       [12., 12., 12., 12.],
       [21., 21., 21., 21.],
       [30., 30., 30., 30.]])

In [37]:
a.dot(b)

array([[ 3.,  3.,  3.,  3.],
       [12., 12., 12., 12.],
       [21., 21., 21., 21.],
       [30., 30., 30., 30.]])

In [38]:
a.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [39]:
np.transpose(a)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

随机数生成

In [41]:
samp = np.random.random((3,2))#生成的是三行两列的从0到1的随机数
samp

array([[0.48195767, 0.33235437],
       [0.74739336, 0.80592982],
       [0.03596625, 0.60814583]])

In [45]:
samp2 = np.random.normal(size=(3,2))#生成服从标准正太分布的随机数
samp2

array([[-0.41336186, -0.78836009],
       [ 1.29236735, -1.31956966],
       [ 0.93381892,  0.98471489]])

In [46]:
samp3 = np.random.randint(0,10,size=(3,2))#生成三行两列整数随机数
samp3

array([[6, 2],
       [3, 7],
       [0, 8]])

In [47]:
np.sum(samp)#求和

3.0117473144867954

In [48]:
np.min(samp)#求最小值

0.0359662526097706

In [50]:
np.max(samp)#求最大值

0.8059298249911602

In [51]:
samp

array([[0.48195767, 0.33235437],
       [0.74739336, 0.80592982],
       [0.03596625, 0.60814583]])

In [52]:
np.sum(samp,axis=0)#对列求和

array([1.26531729, 1.74643003])

In [53]:
np.sum(samp,axis=1)#对行求和

array([0.81431204, 1.55332319, 0.64411209])

In [54]:
np.argmax(samp)#返回最大值的索引

3

In [55]:
np.argmin(samp)#最小值索引

4

In [56]:
np.mean(samp)

0.5019578857477992

In [57]:
samp.mean()

0.5019578857477992

In [58]:
np.median(samp)#中位数

0.5450517530205594

In [59]:
np.sqrt(samp)#求开方

array([[0.69423171, 0.57650184],
       [0.86451915, 0.89773594],
       [0.18964771, 0.77983706]])

In [60]:
a = np.random.randint(0,10,size=(1,10))
a 

array([[8, 1, 9, 8, 1, 5, 0, 3, 2, 4]])

In [61]:
np.sort(a)

array([[0, 1, 1, 2, 3, 4, 5, 8, 8, 9]])

In [62]:
np.sort(samp)#对每一行排序

array([[0.33235437, 0.48195767],
       [0.74739336, 0.80592982],
       [0.03596625, 0.60814583]])

In [63]:
samp

array([[0.48195767, 0.33235437],
       [0.74739336, 0.80592982],
       [0.03596625, 0.60814583]])

In [65]:
np.clip(samp,2,7)#对samp操作，小于2的数为2，大于7的数为7

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [67]:
a = np.arange(2,14)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [68]:
a[2]#index=2位置的值

4

In [69]:
a[2::2]#从index=2开始以步长为2提取数据

array([ 4,  6,  8, 10, 12])

In [70]:
a[1:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [71]:
a[:-2]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [72]:
a[-2:]#取最后两个数据

array([12, 13])

In [74]:
b = a.reshape(3,4)
b

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [75]:
b[1]#index为1的那一行

array([6, 7, 8, 9])

In [76]:
b[1][2]

8

In [78]:
b[1,2]#取行index=1，列index为2的元素

8

In [79]:
b[:,2]#取出所有行中列index=2的值

array([ 4,  8, 12])

In [81]:
for i in b:#行迭代
    print(i)

[2 3 4 5]
[6 7 8 9]
[10 11 12 13]


In [82]:
for i in b.T:#迭代列
    print(i)

[ 2  6 10]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]


In [85]:
for i in b.flat:#迭代每个元素，扁平化处理
    print(i)

2
3
4
5
6
7
8
9
10
11
12
13


In [87]:
a = np.array([1,2,3])
b = np.array([2,3,4])
c = np.vstack((a,b))#垂直合并
c

array([[1, 2, 3],
       [2, 3, 4]])

In [88]:
c = np.hstack((a,b))#水平合并
c

array([1, 2, 3, 2, 3, 4])

In [89]:
c.dtype

dtype('int32')

In [90]:
type(c)

numpy.ndarray

In [91]:
c.shape#一维的ndarray

(6,)

## 使用concatenate合并的ndarray必须有相同的shape

In [93]:
a = np.concatenate((a,b))
a

array([1, 2, 3, 2, 3, 4])

In [94]:
a = np.concatenate((a,b),axis=0)#纵向合并
a

array([1, 2, 3, 2, 3, 4, 2, 3, 4])

In [98]:
a1 = np.random.randint(0,100,size=(4,3))
a2 = np.random.randint(0,10,size=(4,3))
print(a1)
print(a2)

[[73  2 77]
 [66 63 86]
 [59 14 84]
 [90 73 87]]
[[0 6 5]
 [2 5 6]
 [7 5 0]
 [8 3 6]]


In [99]:
res1 = np.concatenate((a1,a2),axis=0)#纵向合并
res1

array([[73,  2, 77],
       [66, 63, 86],
       [59, 14, 84],
       [90, 73, 87],
       [ 0,  6,  5],
       [ 2,  5,  6],
       [ 7,  5,  0],
       [ 8,  3,  6]])

In [100]:
res2 = np.concatenate((a1,a2),axis=1)#横向合并
res2

array([[73,  2, 77,  0,  6,  5],
       [66, 63, 86,  2,  5,  6],
       [59, 14, 84,  7,  5,  0],
       [90, 73, 87,  8,  3,  6]])

AxisError: axis 1 is out of bounds for array of dimension 1

In [103]:
a = np.array([1,2,3])
a.shape

(3,)

In [104]:
a.T

array([1, 2, 3])

In [105]:
a_new = a[np.newaxis,:]
a_new

array([[1, 2, 3]])

In [107]:
a_new.shape

(1, 3)

In [108]:
a_2 = a[:,np.newaxis]
a_2

array([[1],
       [2],
       [3]])

In [109]:
a_2.shape

(3, 1)

In [110]:
a3 = np.atleast_2d(a)
a3

array([[1, 2, 3]])

In [111]:
a4 = np.atleast_3d(a)
a4

array([[[1],
        [2],
        [3]]])

## array分割

In [113]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
arr1,arr2 = np.split(arr,2,axis=1)#垂直方向切割为两个ndarray
print(arr1)
print(arr2)

[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [117]:
a,b,c = np.split(arr,3,axis=0)#水平方向分割为3份
print(a)
print(b)
print(c)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]


In [118]:
arr1,arr2,arr3 = np.array_split(arr,3,axis=1)#水平方向不等分割
print(arr1)
print(arr2)
print(arr3)

[[0 1]
 [4 5]
 [8 9]]
[[ 2]
 [ 6]
 [10]]
[[ 3]
 [ 7]
 [11]]


In [120]:
arr1, arr2,arr3 = np.vsplit(arr,3)
print(arr1)
print(arr2)
print(arr3)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]


In [121]:
arr1, arr2 = np.hsplit(arr,2)
print(arr1)
print(arr2)

[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


## numpy的浅拷贝和深拷贝

In [122]:
a = np.arange(5)
a.shape

(5,)

In [123]:
a

array([0, 1, 2, 3, 4])

In [124]:
b = a

In [125]:
b[0] = 5
a,b

(array([5, 1, 2, 3, 4]), array([5, 1, 2, 3, 4]))

In [126]:
c = a.copy()
c[1] =100

In [127]:
c,a

(array([  5, 100,   2,   3,   4]), array([5, 1, 2, 3, 4]))